# Parameters which usually need to be changed:
# --------------------------------------
# general_config
#   pipeline: train_valid, train_cv, pred
#   num_epochs: max epoch 
#   result_path: path to save experiment result, {} will be filled with model name by default
# model_config
# data_config
#   batch_size
# --------------------------------------

general_config:
  pipeline: ['train_cv']
  gpus: 0
  num_epochs: 200
  global_seed: 42
  result_path: result/110_12/{}

model_config:
  model_name: S_ALL
  model: v8


data_config:
  dataset: kaggle_ventilator
  processor: v1
  batch_size: 128
  train_data_path: /content/drive/MyDrive/Colab Notebooks/vent_tf/vent_tf/data/train.csv
  test_data_path: /content/drive/MyDrive/Colab Notebooks/vent_tf/vent_tf/data/test.csv
  R_C: '50_20'
  remark: model is v8

bark_config:
  url_prefix: https://api.day.app/isQca3F22zJurMU5DuCaiG
